# Generated by Django 5.0.14 on 2026-02-13 08:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoachProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("certification", models.CharField(blank=True, max_length=255)),
                ("years_experience", models.PositiveIntegerField(default=0)),
                ("hourly_rate", models.PositiveIntegerField(blank=True, null=True)),
                ("specialties", models.JSONField(blank=True, default=list)),
                ("bio", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, upload_to="avatars/coaches/")),
                ("city", models.CharField(blank=True, max_length=100)),
                ("available_days", models.JSONField(blank=True, default=list)),
                ("total_students", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "coach profile",
                "verbose_name_plural": "coach profiles",
            },
        ),
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ntrp_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=2.5,
                        help_text="NTRP rating from 1.0 (beginner) to 7.0 (pro)",
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(7.0),
                        ],
                    ),
                ),
                (
                    "play_style",
                    models.CharField(
                        choices=[
                            ("baseline", "Baseline Player"),
                            ("serve_volley", "Serve and Volley"),
                            ("all_court", "All Court Player"),
                            ("counter_puncher", "Counter Puncher"),
                        ],
                        default="all_court",
                        max_length=20,
                    ),
                ),
                (
                    "handedness",
                    models.CharField(
                        choices=[
                            ("right", "Right-handed"),
                            ("left", "Left-handed"),
                            ("both", "Ambidextrous"),
                        ],
                        default="right",
                        max_length=10,
                    ),
                ),
                ("years_experience", models.PositiveIntegerField(default=0)),
                ("height_cm", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_kg", models.PositiveIntegerField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, upload_to="avatars/players/")),
                ("city", models.CharField(blank=True, max_length=100)),
                ("matches_played", models.PositiveIntegerField(default=0)),
                ("matches_won", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "player profile",
                "verbose_name_plural": "player profiles",
            },
        ),
    ]
