# Generated by Django 5.0.14 on 2026-02-13 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coachprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="coachprofile",
            index=models.Index(
                fields=["is_verified"], name="profiles_co_is_veri_c4880e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coachprofile",
            index=models.Index(fields=["city"], name="profiles_co_city_76633b_idx"),
        ),
        migrations.AddIndex(
            model_name="coachprofile",
            index=models.Index(
                fields=["hourly_rate"], name="profiles_co_hourly__b141f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerprofile",
            index=models.Index(
                fields=["ntrp_rating"], name="profiles_pl_ntrp_ra_83b4c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerprofile",
            index=models.Index(fields=["city"], name="profiles_pl_city_5b50fa_idx"),
        ),
        migrations.AddConstraint(
            model_name="playerprofile",
            constraint=models.CheckConstraint(
                check=models.Q(("ntrp_rating__gte", 1.0), ("ntrp_rating__lte", 7.0)),
                name="valid_ntrp_rating",
            ),
        ),
    ]
