# Generated by Django 5.0.14 on 2026-02-14 12:28

import varzesha.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneverificationcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='baseuser',
            name='users_baseu_phone_b2190d_idx',
        ),
        migrations.RemoveIndex(
            model_name='baseuser',
            name='users_baseu_is_phon_7aacf4_idx',
        ),
        migrations.RemoveIndex(
            model_name='phoneverificationcode',
            name='users_phone_phone_62430e_idx',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Verified coach badge'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phoneverificationcode',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phoneverificationcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='is_coach',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='is_phone_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='phone',
            field=models.CharField(db_index=True, help_text='Iranian mobile number (e.g., 09123456789)', max_length=13, unique=True, validators=[varzesha.users.models.validate_iranian_phone]),
        ),
        migrations.AlterField(
            model_name='phoneverificationcode',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='phoneverificationcode',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='phoneverificationcode',
            name='phone',
            field=models.CharField(db_index=True, max_length=13),
        ),
        migrations.AddIndex(
            model_name='baseuser',
            index=models.Index(fields=['phone', 'is_phone_verified'], name='users_baseu_phone_78e009_idx'),
        ),
        migrations.AddIndex(
            model_name='baseuser',
            index=models.Index(fields=['is_coach', 'is_verified'], name='users_baseu_is_coac_e9bec5_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverificationcode',
            index=models.Index(fields=['phone', 'is_used', 'expires_at'], name='users_phone_phone_26b195_idx'),
        ),
        migrations.AddConstraint(
            model_name='baseuser',
            constraint=models.CheckConstraint(check=models.Q(('phone__regex', '^0?9\\d{9}$')), name='valid_phone_format', violation_error_message='Phone number must be valid Iranian format'),
        ),
    ]
