# Generated by Django 5.0.14 on 2026-02-13 08:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("address", models.TextField()),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "surface_type",
                    models.CharField(
                        choices=[
                            ("hard", "Hard Court"),
                            ("clay", "Clay Court"),
                            ("grass", "Grass Court"),
                            ("carpet", "Carpet Court"),
                            ("artificial", "Artificial Grass"),
                        ],
                        default="hard",
                        max_length=20,
                    ),
                ),
                ("indoor", models.BooleanField(default=False)),
                ("has_lights", models.BooleanField(default=False)),
                (
                    "price_per_hour",
                    models.PositiveIntegerField(
                        help_text="Price per hour in Iranian Toman"
                    ),
                ),
                ("has_parking", models.BooleanField(default=False)),
                ("has_showers", models.BooleanField(default=False)),
                ("has_locker_room", models.BooleanField(default=False)),
                ("has_equipment_rental", models.BooleanField(default=False)),
                ("phone", models.CharField(blank=True, max_length=13)),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("main_image", models.ImageField(blank=True, upload_to="courts/")),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "court",
                "verbose_name_plural": "courts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["city", "is_active"], name="courts_cour_city_42616f_idx"
                    ),
                    models.Index(
                        fields=["surface_type"], name="courts_cour_surface_0d8e19_idx"
                    ),
                    models.Index(
                        fields=["price_per_hour"], name="courts_cour_price_p_362a7f_idx"
                    ),
                    models.Index(
                        fields=["average_rating"], name="courts_cour_average_95b15b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CourtAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        help_text="0=Monday, 6=Sunday",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="courts.court",
                    ),
                ),
            ],
            options={
                "verbose_name": "court availability",
                "verbose_name_plural": "court availabilities",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="CourtReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="courts.court",
                    ),
                ),
            ],
            options={
                "verbose_name": "court review",
                "verbose_name_plural": "court reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
