# Generated by Django 5.0.14 on 2026-02-14 12:28

import django.contrib.postgres.indexes
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='court',
            name='courts_cour_surface_0d8e19_idx',
        ),
        migrations.RemoveIndex(
            model_name='court',
            name='courts_cour_price_p_362a7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='court',
            name='courts_cour_average_95b15b_idx',
        ),
        migrations.AlterField(
            model_name='court',
            name='has_lights',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='court',
            name='has_parking',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='court',
            name='has_showers',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='court',
            name='indoor',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='court',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='courts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='court',
            name='price_per_hour',
            field=models.PositiveIntegerField(db_index=True, help_text='Price per hour in Iranian Toman'),
        ),
        migrations.AlterField(
            model_name='court',
            name='surface_type',
            field=models.CharField(choices=[('hard', 'Hard Court'), ('clay', 'Clay Court'), ('grass', 'Grass Court'), ('carpet', 'Carpet Court'), ('artificial', 'Artificial Grass')], db_index=True, default='hard', max_length=20),
        ),
        migrations.AlterField(
            model_name='courtavailability',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='courtavailability',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['surface_type', 'is_active'], name='courts_cour_surface_389c30_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['price_per_hour', 'is_active'], name='courts_cour_price_p_236c72_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['average_rating', 'is_active'], name='courts_cour_average_03cdcf_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'address', 'city'], name='court_search_gin', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='courtavailability',
            index=models.Index(fields=['court', 'day_of_week', 'is_available'], name='courts_cour_court_i_97e779_idx'),
        ),
        migrations.AddIndex(
            model_name='courtreview',
            index=models.Index(fields=['court', 'created_at'], name='courts_cour_court_i_6f520d_idx'),
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.CheckConstraint(check=models.Q(('price_per_hour__gte', 0)), name='positive_price'),
        ),
        migrations.AddConstraint(
            model_name='courtavailability',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', models.F('end_time'))), name='valid_time_range'),
        ),
    ]
