# Generated by Django 5.0.14 on 2026-02-13 08:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("forehand", "Forehand"),
                            ("backhand", "Backhand"),
                            ("serve", "Serve"),
                            ("volley", "Volley"),
                            ("footwork", "Footwork"),
                            ("conditioning", "Physical Conditioning"),
                            ("strategy", "Strategy"),
                            ("warmup", "Warm-up"),
                        ],
                        default="forehand",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("professional", "Professional"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=15, help_text="Recommended duration for this drill"
                    ),
                ),
                (
                    "equipment_needed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of equipment needed (e.g., ['cones', 'balls'])",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="Step-by-step instructions for the drill"
                    ),
                ),
                (
                    "tips",
                    models.TextField(
                        blank=True,
                        help_text="Coaching tips and common mistakes to avoid",
                    ),
                ),
                ("video_url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="drills/")),
                ("is_public", models.BooleanField(default=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "drill",
                "verbose_name_plural": "drills",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingDrill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sets", models.PositiveIntegerField(default=1)),
                ("reps_per_set", models.PositiveIntegerField(default=10)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "success_rate",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Success rate percentage",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MinValueValidator(100),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "training drill",
                "verbose_name_plural": "training drills",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "target_value",
                    models.PositiveIntegerField(
                        help_text="Target value (e.g., 10 sessions, 1000 serves)"
                    ),
                ),
                ("current_value", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "training goal",
                "verbose_name_plural": "training goals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("date", models.DateField()),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Total session duration in minutes",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "intensity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("location_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "feeling_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="How did you feel? 1-5",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MinValueValidator(5),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "training session",
                "verbose_name_plural": "training sessions",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
