# Generated by Django 5.0.14 on 2026-02-13 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courts", "0002_initial"),
        ("trainings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="drill",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_drills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trainingdrill",
            name="drill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_instances",
                to="trainings.drill",
            ),
        ),
        migrations.AddField(
            model_name="traininggoal",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="court",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_sessions",
                to="courts.court",
            ),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trainingdrill",
            name="training",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drills",
                to="trainings.trainingsession",
            ),
        ),
        migrations.AddIndex(
            model_name="drill",
            index=models.Index(
                fields=["category"], name="trainings_d_categor_b65352_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drill",
            index=models.Index(
                fields=["difficulty"], name="trainings_d_difficu_d6ffbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drill",
            index=models.Index(
                fields=["is_public"], name="trainings_d_is_publ_58aa40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingsession",
            index=models.Index(
                fields=["player", "date"], name="trainings_t_player__30d6c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingsession",
            index=models.Index(fields=["date"], name="trainings_t_date_d529d2_idx"),
        ),
    ]
