# Generated by Django 5.0.14 on 2026-02-14 12:28

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_remove_court_courts_cour_surface_0d8e19_idx_and_more'),
        ('trainings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='drill',
            name='trainings_d_categor_b65352_idx',
        ),
        migrations.RemoveIndex(
            model_name='drill',
            name='trainings_d_difficu_d6ffbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='drill',
            name='trainings_d_is_publ_58aa40_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainingsession',
            name='trainings_t_date_d529d2_idx',
        ),
        migrations.AlterField(
            model_name='drill',
            name='category',
            field=models.CharField(choices=[('forehand', 'Forehand'), ('backhand', 'Backhand'), ('serve', 'Serve'), ('volley', 'Volley'), ('footwork', 'Footwork'), ('conditioning', 'Physical Conditioning'), ('strategy', 'Strategy'), ('warmup', 'Warm-up')], db_index=True, default='forehand', max_length=20),
        ),
        migrations.AlterField(
            model_name='drill',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], db_index=True, default='intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='drill',
            name='image',
            field=models.ImageField(blank=True, upload_to='drills/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='drill',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='trainingdrill',
            name='success_rate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Success rate percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='traininggoal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='feeling_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How did you feel? 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='drill',
            index=models.Index(fields=['category', 'is_public'], name='trainings_d_categor_7a7fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='drill',
            index=models.Index(fields=['difficulty', 'is_public'], name='trainings_d_difficu_796968_idx'),
        ),
        migrations.AddIndex(
            model_name='traininggoal',
            index=models.Index(fields=['player', 'status'], name='trainings_t_player__4d1619_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['date', 'player'], name='trainings_t_date_e6d35f_idx'),
        ),
    ]
