# Generated by Django 5.0.14 on 2026-02-13 08:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "match_type",
                    models.CharField(
                        choices=[("singles", "Singles"), ("doubles", "Doubles")],
                        default="singles",
                        max_length=10,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=90, help_text="Expected duration in minutes"
                    ),
                ),
                (
                    "court_name",
                    models.CharField(
                        blank=True,
                        help_text="Custom court name if not using registered court",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("organizer_score", models.PositiveIntegerField(blank=True, null=True)),
                ("opponent_score", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "set_scores",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of sets: [[6,4], [3,6], [6,2]]",
                    ),
                ),
                (
                    "ntrp_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Minimum NTRP rating for opponent",
                        max_digits=2,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1.0)],
                    ),
                ),
                (
                    "ntrp_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Maximum NTRP rating for opponent",
                        max_digits=2,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1.0)],
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Public matches are visible to all players",
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "match",
                "verbose_name_plural": "matches",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "match comment",
                "verbose_name_plural": "match comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "match invitation",
                "verbose_name_plural": "match invitations",
                "ordering": ["-created_at"],
            },
        ),
    ]
