# Generated by Django 5.0.14 on 2026-02-13 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courts", "0002_initial"),
        ("matches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_matches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="court",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches",
                to="courts.court",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="opponent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_matches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_matches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matchcomment",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="matches.match",
            ),
        ),
        migrations.AddField(
            model_name="matchcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matchinvitation",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matchinvitation",
            name="invited_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matchinvitation",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="matches.match",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["organizer", "status"], name="matches_mat_organiz_9c2e8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["opponent", "status"], name="matches_mat_opponen_67b785_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["scheduled_at"], name="matches_mat_schedul_bcd8bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["status", "is_public"], name="matches_mat_status_82afc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["court"], name="matches_mat_court_i_20e77a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="matchinvitation",
            unique_together={("match", "invited_user")},
        ),
    ]
