# Generated by Django 5.0.14 on 2026-02-14 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_remove_court_courts_cour_surface_0d8e19_idx_and_more'),
        ('matches', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='matches_mat_schedul_bcd8bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='matches_mat_status_82afc8_idx',
        ),
        migrations.AlterField(
            model_name='match',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Public matches are visible to all players'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('singles', 'Singles'), ('doubles', 'Doubles')], db_index=True, default='singles', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='scheduled_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['scheduled_at', 'status'], name='matches_mat_schedul_f312ff_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'is_public', 'scheduled_at'], name='matches_mat_status_3b3e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='matchinvitation',
            index=models.Index(fields=['invited_user', 'status'], name='matches_mat_invited_0eb182_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(check=models.Q(('ntrp_min__isnull', True), ('ntrp_max__isnull', True), ('ntrp_min__lte', models.F('ntrp_max')), _connector='OR'), name='valid_ntrp_range', violation_error_message='NTRP min must be less than or equal to NTRP max'),
        ),
    ]
